// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/assets/add": {
            "post": {
                "description": "增加资产",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset-资产设备管理雄相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待添加资产D",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.AssetsModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/assets/delete": {
            "post": {
                "description": "根据资产IDs删除资产信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset-资产设备管理雄相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除资产IDs",
                        "name": "ids",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/assets/deprecate": {
            "post": {
                "description": "根据资产IDs删除资产信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset-资产设备管理雄相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除资产IDs",
                        "name": "ids",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/assets/export": {
            "post": {
                "description": "导出资产信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset-资产设备管理雄相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "需要导出的ids",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/assets/getById": {
            "get": {
                "description": "根据资产ID获取资产信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset-资产设备管理雄相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "资产ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/assets/import": {
            "post": {
                "description": "导入资产信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset-资产设备管理雄相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "file",
                        "description": "文件上传",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/assets/page": {
            "post": {
                "description": "分页查询资产信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset-资产设备管理雄相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待查询资产信息",
                        "name": "req",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.AssetsQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AssetsVO"
                        }
                    }
                }
            }
        },
        "/api/assets/template": {
            "get": {
                "description": "获取导入资产信息模板",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset-资产设备管理雄相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/assets/type/add": {
            "post": {
                "description": "增加资产类型",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AssetType-资产类型管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待添加资产类型",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SwustAssetType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/assets/type/delete": {
            "post": {
                "description": "根据资产IDs删除资产类型信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AssetType-资产类型管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除资产IDs",
                        "name": "ids",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/assets/type/getById": {
            "get": {
                "description": "根据资产类型ID获取供资产信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AssetType-资产类型管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "资产ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwustAssetType"
                        }
                    }
                }
            }
        },
        "/api/assets/type/page": {
            "post": {
                "description": "分页查询资产类型信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AssetType-资产类型管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "筛选条件",
                        "name": "req",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.TypeQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwustAssetType"
                        }
                    }
                }
            }
        },
        "/api/assets/type/update": {
            "post": {
                "description": "更新资产类型信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AssetType-资产类型管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待添加资产类型",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SwustAssetType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/assets/update": {
            "post": {
                "description": "更新资产信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Asset-资产设备管理雄相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待添加资产",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.AssetsModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/order/add": {
            "post": {
                "description": "增加采购信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order-采购信息管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "采购单信息",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.OrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/order/approve": {
            "post": {
                "description": "审批采购信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order-采购信息管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待审批订单ID",
                        "name": "req",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.ApproveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/order/delete": {
            "post": {
                "description": "根据采购IDs删除采购信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order-采购信息管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除采购信息IDs",
                        "name": "ids",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/order/getById": {
            "get": {
                "description": "根据订单ID获取采购信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order-采购信息管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/order/page": {
            "post": {
                "description": "分页查询资产信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order-采购信息管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除资产IDs",
                        "name": "req",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.OrderQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.PageResponseModel"
                        }
                    }
                }
            }
        },
        "/api/order/update": {
            "post": {
                "description": "更新资产信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order-采购信息管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待更新采购单信息",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.OrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/producer/add": {
            "post": {
                "description": "增加供销商",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Producer-供销商管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待添加厂商ID",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SwustProducer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/producer/delete": {
            "post": {
                "description": "根据供销商IDs删除供销商信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Producer-供销商管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除供销商IDs",
                        "name": "ids",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/producer/getById": {
            "get": {
                "description": "根据供销商ID获取供销商信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Producer-供销商管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "资产ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/producer/page": {
            "post": {
                "description": "分页查询供销商信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Producer-供销商管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "筛选条件",
                        "name": "req",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.ProducerQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.PageResponseModel"
                        }
                    }
                }
            }
        },
        "/api/producer/update": {
            "post": {
                "description": "更新供销商信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Producer-供销商管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待添加供销商",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SwustProducer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/room/add": {
            "post": {
                "description": "增加实验室",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room-实验室管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待添加实验室",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SwustRoomModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/room/delete": {
            "post": {
                "description": "根据实验室IDs删除实验室信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room-实验室管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除资产IDs",
                        "name": "ids",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/room/getById": {
            "get": {
                "description": "根据实验室ID获取实验室信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room-实验室管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "资产ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwustRoomModel"
                        }
                    }
                }
            }
        },
        "/api/room/listLocation": {
            "get": {
                "description": "获取所有实验室楼栋信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room-实验室管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwustRoomModel"
                        }
                    }
                }
            }
        },
        "/api/room/page": {
            "post": {
                "description": "分页查询实验室信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room-实验室管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除资产IDs",
                        "name": "req",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.AssetsQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.PageResponseModel"
                        }
                    }
                }
            }
        },
        "/api/room/update": {
            "post": {
                "description": "更新实验室信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room-实验室管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待添加资产",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SwustRoomModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/statistic/countAssetsApplyTrend": {
            "get": {
                "description": "获取资产申请趋势统计",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistic-统计相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StatisticModel"
                        }
                    }
                }
            }
        },
        "/api/statistic/countAssetsByStatus": {
            "get": {
                "description": "根据资产状态统计",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistic-统计相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StatisticModel"
                        }
                    }
                }
            }
        },
        "/api/statistic/countAssetsByType": {
            "get": {
                "description": "根据资产类型统计",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistic-统计相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StatisticModel"
                        }
                    }
                }
            }
        },
        "/api/statistic/countAssetsDepTrend": {
            "get": {
                "description": "获取资产报废趋势统计",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistic-统计相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StatisticModel"
                        }
                    }
                }
            }
        },
        "/api/statistic/countOrderDetail": {
            "get": {
                "description": "获取资产报废趋势统计",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistic-统计相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StatisticModel"
                        }
                    }
                }
            }
        },
        "/api/system/log/delete": {
            "post": {
                "description": "根据资产IDs删除资产信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemLog-系统日志管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "日志凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除日志IDs",
                        "name": "ids",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/log/getById": {
            "get": {
                "description": "根据日志ID获取日志信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemLog-系统日志管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "日志凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "资产ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/log/page": {
            "post": {
                "description": "分页查询日志信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemLog-系统日志管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "日志凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除资产IDs",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SystemLogQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.PageResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/menu/list": {
            "get": {
                "description": "获取菜单树",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemMenu-系统菜单管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/role/getRolesByUserId/{userId}": {
            "get": {
                "description": "分页查询权限信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemRole-系统权限管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "权限凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SwustSystemRole"
                            }
                        }
                    }
                }
            }
        },
        "/api/system/role/modify/{userId}": {
            "post": {
                "description": "分配权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemRole-系统权限管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户Id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "权限凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "权限IDs",
                        "name": "roles",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/role/page": {
            "post": {
                "description": "分页查询权限信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemRole-系统权限管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "权限凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.PageResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/user/add": {
            "post": {
                "description": "增加用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemUser-系统用户管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待添加用户",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SystemUserModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/user/delete": {
            "post": {
                "description": "根据资产IDs删除资产信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemUser-系统用户管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除用户IDs",
                        "name": "ids",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/user/getById": {
            "get": {
                "description": "根据用户ID获取用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemUser-系统用户管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "资产ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/user/getCurrentUser": {
            "get": {
                "description": "获取当前登录用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemUser-系统用户管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SystemUserModel"
                        }
                    }
                }
            }
        },
        "/api/system/user/login": {
            "post": {
                "description": "登录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemUser-系统用户管理相关接口"
                ],
                "parameters": [
                    {
                        "description": "账号密码",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/user/logout": {
            "post": {
                "description": "退出登录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemUser-系统用户管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/user/page": {
            "post": {
                "description": "分页查询用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemUser-系统用户管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待删除资产IDs",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SystemUserQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.PageResponseModel"
                        }
                    }
                }
            }
        },
        "/api/system/user/update": {
            "post": {
                "description": "更新用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SystemUser-系统用户管理相关接口"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户凭证",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "待添加资产",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SystemUserModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.ResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.PageModel": {
            "type": "object",
            "properties": {
                "pageNum": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "分页大小",
                    "type": "integer"
                }
            }
        },
        "common.PageResponseModel": {
            "type": "object",
            "properties": {
                "data": {},
                "page": {
                    "$ref": "#/definitions/common.PageModel"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "common.ResponseModel": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "models.ApproveReq": {
            "type": "object",
            "properties": {
                "approveTime": {
                    "description": "审批时间",
                    "type": "string"
                },
                "orderId": {
                    "description": "采购单ID",
                    "type": "string"
                },
                "reason": {
                    "description": "驳回理由",
                    "type": "string"
                },
                "status": {
                    "description": "审核意见 -1 拒绝 1 同意",
                    "type": "integer"
                },
                "userId": {
                    "description": "审批人ID",
                    "type": "string"
                }
            }
        },
        "models.AssetsModel": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "资产编码",
                    "type": "string"
                },
                "comment": {
                    "description": "备注",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "orderID": {
                    "description": "采购编号",
                    "type": "string"
                },
                "price": {
                    "description": "价格",
                    "type": "number"
                },
                "producerID": {
                    "description": "厂商ID",
                    "type": "string"
                },
                "productionTime": {
                    "description": "生产日期",
                    "type": "string"
                },
                "serviceLength": {
                    "description": "服役年限",
                    "type": "integer"
                },
                "status": {
                    "description": "0 在用 1 故障 2 维修 3 报废",
                    "type": "integer"
                },
                "typeID": {
                    "description": "所在房间",
                    "type": "string"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "userID": {
                    "description": "责任人",
                    "type": "string"
                }
            }
        },
        "models.AssetsQueryRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "资产编码",
                    "type": "string"
                },
                "comment": {
                    "description": "备注",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "endTime": {
                    "description": "结束时间",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "ids": {
                    "description": "根据传入ids查询",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "orderID": {
                    "description": "采购编号",
                    "type": "string"
                },
                "pageNum": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "分页大小",
                    "type": "integer"
                },
                "price": {
                    "description": "价格",
                    "type": "number"
                },
                "producerID": {
                    "description": "厂商ID",
                    "type": "string"
                },
                "productionTime": {
                    "description": "生产日期",
                    "type": "string"
                },
                "serviceLength": {
                    "description": "服役年限",
                    "type": "integer"
                },
                "status": {
                    "description": "0 在用 1 故障 2 维修 3 报废",
                    "type": "integer"
                },
                "typeID": {
                    "description": "所在房间",
                    "type": "string"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "userID": {
                    "description": "责任人",
                    "type": "string"
                }
            }
        },
        "models.AssetsVO": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "资产编码",
                    "type": "string"
                },
                "comment": {
                    "description": "备注",
                    "type": "string"
                },
                "header": {
                    "description": "负责人",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "orderID": {
                    "description": "采购编号",
                    "type": "string"
                },
                "price": {
                    "description": "价格",
                    "type": "number"
                },
                "producerName": {
                    "description": "供应商名字",
                    "type": "string"
                },
                "productionTime": {
                    "description": "生产日期",
                    "type": "string"
                },
                "quantity": {
                    "description": "数量",
                    "type": "string",
                    "example": "0"
                },
                "retireMentTime": {
                    "description": "报废退役年限",
                    "type": "string"
                },
                "serviceLength": {
                    "description": "服役年限",
                    "type": "integer"
                },
                "status": {
                    "description": "0 在用 1 故障 2 维修 3 报废",
                    "type": "integer"
                },
                "typeName": {
                    "description": "RoomName       *string       ` + "`" + `gorm:\"column:room_name;type:varchar(25)\" json:\"roomName\"` + "`" + `                     // 房间名称\nFloor          *int64        ` + "`" + `gorm:\"column:floor;type:int\" json:\"floor\"` + "`" + `                                    // 楼层\nRoomNum        *string       ` + "`" + `gorm:\"column:number;type:varchar(4)\" json:\"room_num\"` + "`" + `                         // 房间号\nAddress       *string       ` + "`" + `gorm:\"column:location;type:varchar(25)\" json:\"location\"` + "`" + `                      // 房间位置",
                    "type": "string"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "userID": {
                    "description": "责任人",
                    "type": "string"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "用户名",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "models.OrderAssetRequest": {
            "type": "object",
            "properties": {
                "applyTime": {
                    "description": "UserID     *string    ` + "`" + `gorm:\"column:user_id;type:varchar(19)\" json:\"userID\"` + "`" + `                       // 责任人",
                    "type": "string"
                },
                "comment": {
                    "description": "备注",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orderId": {
                    "description": "采购订单id",
                    "type": "string"
                },
                "orderTime": {
                    "description": "采购时间",
                    "type": "string"
                },
                "producerId": {
                    "description": "供应商名字",
                    "type": "string"
                },
                "quantity": {
                    "description": "数量",
                    "type": "string",
                    "example": "0"
                },
                "typeId": {
                    "description": "类型名称",
                    "type": "string"
                }
            }
        },
        "models.OrderQueryRequest": {
            "type": "object",
            "properties": {
                "applyUser": {
                    "description": "申请人名称",
                    "type": "string"
                },
                "endTime": {
                    "description": "申请结束时间",
                    "type": "string"
                },
                "pageNum": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "分页大小",
                    "type": "integer"
                },
                "startTime": {
                    "description": "申请起始时间",
                    "type": "string"
                },
                "status": {
                    "description": "采购单状态",
                    "type": "integer"
                }
            }
        },
        "models.OrderRequest": {
            "type": "object",
            "properties": {
                "assets": {
                    "description": "采购明细信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OrderAssetRequest"
                    }
                },
                "orderName": {
                    "description": "采购事由",
                    "type": "string"
                },
                "user_id": {
                    "description": "采购申请人",
                    "type": "string"
                }
            }
        },
        "models.ProducerQueryRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "厂商位置",
                    "type": "string"
                },
                "contact_user": {
                    "description": "联络人",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "pageNum": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "分页大小",
                    "type": "integer"
                },
                "phoneNumber": {
                    "description": "手机号",
                    "type": "string"
                }
            }
        },
        "models.StatisticModel": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "value": {
                    "description": "数量",
                    "type": "integer"
                }
            }
        },
        "models.SwustAssetType": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                }
            }
        },
        "models.SwustProducer": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "联络地址",
                    "type": "string"
                },
                "contact_phone": {
                    "description": "联系电话号码",
                    "type": "string"
                },
                "contact_user": {
                    "description": "联络人",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                }
            }
        },
        "models.SwustRoomModel": {
            "type": "object",
            "properties": {
                "floor": {
                    "description": "楼层",
                    "type": "integer"
                },
                "header": {
                    "description": "房间负责人Id",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "location": {
                    "description": "房间位置",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "room_num": {
                    "description": "房间号",
                    "type": "string"
                }
            }
        },
        "models.SwustSystemRole": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父节点id",
                    "type": "string"
                },
                "resource": {
                    "description": "权限关联资源",
                    "type": "string"
                }
            }
        },
        "models.SystemLogQueryRequest": {
            "type": "object",
            "properties": {
                "endTime": {
                    "description": "结束时间",
                    "type": "string"
                },
                "event": {
                    "description": "事件类型",
                    "type": "integer"
                },
                "operateUser": {
                    "description": "操作人",
                    "type": "string"
                },
                "pageNum": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "分页大小",
                    "type": "integer"
                },
                "startTime": {
                    "description": "操作时间",
                    "type": "string"
                }
            }
        },
        "models.SystemUserModel": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "用户名",
                    "type": "string"
                },
                "avatar": {
                    "description": "Role        *string ` + "`" + `gorm:\"column:role;type:text\" json:\"role\"` + "`" + `                       // 权限",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phoneNumber": {
                    "description": "电话号码",
                    "type": "string"
                },
                "salt": {
                    "description": "盐",
                    "type": "string"
                }
            }
        },
        "models.SystemUserQueryRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "pageNum": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "分页大小",
                    "type": "integer"
                },
                "phoneNumber": {
                    "description": "电话号码",
                    "type": "string"
                }
            }
        },
        "models.TypeQueryRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "类型名称",
                    "type": "string"
                },
                "pageNum": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "分页大小",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
